from __future__ import annotations

"""Domain-level reason/status constants used by pipeline summaries."""

TRF_SEMANTIC_SOURCE = "spacy_trf_semantic"

REASON_NONE = ""
REASON_EMPTY_TEXT = "empty_text"
REASON_PARSE_ERROR = "parse_error"
REASON_NOT_REQUESTED = "not_requested"
REASON_SYNC_DISABLED = "sync_disabled"
REASON_NO_CANDIDATES = "no_candidates"
REASON_THIRD_PASS_VALIDATION_BLOCKED = "third_pass_validation_blocked"
REASON_SECOND_PASS_NOT_SYNCED = "second_pass_not_synced"
REASON_THIRD_PASS_NOT_SYNCED = "third_pass_not_synced"
REASON_MWE_PARSER_UNAVAILABLE = "mwe_parser_unavailable"
REASON_SECOND_PASS_FAILED = "second_pass_failed"
REASON_INVALID_SECOND_PASS_PAYLOAD = "invalid_second_pass_payload"
REASON_VALIDATION_REQUIRES_SECOND_PASS = "validation_requires_second_pass"
REASON_VALIDATION_NO_SECOND_PASS_OCCURRENCES = "validation_no_second_pass_occurrences"
REASON_VALIDATION_SECOND_PASS_EMPTY_FALLBACK = "validation_second_pass_empty_fallback"
REASON_VALIDATION_BLOCKED_HIGH_CONFIDENCE_TRF = "validation_blocked_high_confidence_trf"
REASON_VALIDATION_SUSPICIOUS_TRF_UNCERTAIN = "validation_suspicious_trf_uncertain"
REASON_VALIDATION_TRF_NOT_UNCERTAIN = "validation_trf_not_uncertain"
REASON_VALIDATION_NO_TRF_SIGNAL = "validation_no_trf_signal"
REASON_VALIDATION_NO_TRF_SIGNAL_FALLBACK = "validation_no_trf_signal_fallback"
REASON_THIRD_PASS_FAILED = "third_pass_failed"
REASON_INVALID_THIRD_PASS_PAYLOAD = "invalid_third_pass_payload"
REASON_INVALID_OCCURRENCES = "invalid_occurrences"
REASON_MWE_REPOSITORY_UNAVAILABLE = "mwe_repository_unavailable"
REASON_MWE_UPSERT_ERRORS = "mwe_upsert_errors"
REASON_SYNC_TIMEOUT_EXCEEDED = "sync_timeout_exceeded"
REASON_ASYNC_QUEUE_UNAVAILABLE = "async_queue_unavailable"
REASON_QUEUE_FULL = "queue_full"
REASON_ASYNC_SYNC_ENABLED_PERSISTENT = "async_sync_enabled_persistent"
REASON_ASYNC_SYNC_ENABLED_INMEMORY = "async_sync_enabled_inmemory"
